#In the first part of this homework assignment, you will load in a dataframe, clean it up, and get practice manipulating it. In the second part, you will get practice calculating measures of fit/dispersion. Please remember to work on this with your partner and submit a single assignment to Blackboard; one grade will be given to both partners. This is due next week on Thursday at 10h before lecture.

#Part 1: Dataframe clean up and practice

#1 Load in the dataframe "movie_metadata.csv" (Note that the separator used in this file is the tab which is indicated with "\t")
movie_metadata = read.table(file.choose(), header=TRUE, sep="\t", quote="", comment.char="", fill=TRUE)

#2 View a summary of the contents of this dataframe.
str(movie_metadata)

#3 how many NAs are there in the budget column? look up help on the is.na() function in order to figure out how to determine this.
movies_na = is.na(movie_metadata$budget)==TRUE
movies_budget_na = which(movies_na==TRUE); length(movies_budget_na)


#4 create a subset of the dataframe that only includes those rows that are not missing any data. Use this subset from now on.
movie_correct = movie_metadata[complete.cases(movie_metadata),]; movie_correct

#5 for the imdb_score and aspect_ratio columns, replace the commas with dots as the decimal indicator.
movie_without_comma_imdb = gsub(",", ".", movie_correct$imdb_score); movie_without_comma1
movie_without_comma_aspect = gsub(",", ".", movie_correct$aspect_ratio); movie_without_comma_final


#6 now convert these columns to numeric values (see practical activity for hint on how to do this)
movies_with_numeric_imdb = as.numeric(movie_without_comma_imdb); movies_with_numeric_imdb
movies_with_numeric_aspect = as.numeric(movie_without_comma_aspect); movies_with_numeric_aspect
movie_correct$imdb_score = movies_with_numeric_imdb
movie_correct$aspect_ratio = movies_with_numeric_aspect


#7 round the aspect_ratio values to 1 decimal place
movies_aspect_rounded = round(movies_with_numeric_aspect, digits=1)
movie_correct$aspect_ratio = movies_aspect_rounded

#8 sort the dataframe by country, then decreasing by gross (gross refers to the amount of revenue generated by the movie). Use this sorted version in the next questions.
movie_country_gross = movie_correct[order(movie_correct$country),-movie_correct$gross]; movie_country_gross


#9 The row names (which, here, are numbers) are out of order. Replace them with new continuous numbering from 1 to the end of the dataframe.
row.names(movie_country_gross) = seq(nrow(movie_country_gross))

#10 Remove the column movie_imdb_link
movie_country_gross$movie_imdb_link = NULL

#11 Create a new column that adds together the values from the cast_total_facebook_likes and the movie_facebook_likes. call this column "total_facebook_likes"
movie_country_gross$total_facebook_likes = movie_country_gross$cast_total_facebook_likes + movie_country_gross$movie_facebook_likes

#12 Create a subset of all rows that contain 0 likes in at least one of the facebook like-related columns.
movie_no_likes = subset(movie_country_gross, movie_country_gross$director_facebook_likes == 0); movie_no_likes


#13 Save the dataframe (not the subset you just created in 12!) to the file "cleaned_movie_data.csv"  Don't include row names in the saved file
write.table(movie_country_gross, "cleaned_movie_data.csv", quote=FALSE, sep=",", row.names=FALSE)



#Part 2: For the data in the imdb_score column, manually calculate the:

#1 Sum of squared errors:
total_score = gsub(",", ".", movie_metadata$imdb_score); total_score
total_score_final = as.numeric(total_score); total_score_final
mean(total_score_final)
movie_metadata$mean = mean(total_score_final)

score_without_comma = gsub(",", ".", movie_metadata$imdb_score); score_without_comma
score_without_comma_final = as.numeric(score_without_comma); score_without_comma_final
movie_metadata$imdb_score = score_without_comma_final

movie_metadata$deviation = movie_metadata$imdb_score - movie_metadata$mean

movie_metadata$squared_deviation = movie_metadata$deviation^2 

Sum_squared_errors = sum((movie_metadata$imdb_score-mean(movie_metadata$imdb_score))^2); Sum_squared_errors
#2 The variance:
variance = var(movie_metadata$imdb_score); variance

#3 The standard deviation: 
standard_deviation = sqrt(variance); standard_deviation

#4 The standard error:
standard_error = standard_deviation/sqrt(length(movie_metadata$imdb_score)); standard_error

#5 Now verify that your calculation of the standard deviation is correct by using the sd() function.
standard_deviation_function = sd(movie_metadata$imdb_score); standard_deviation_function


#6 Now verfy that your calculation of the standard error is correct. To do this, you will need to install and load the package called "plotrix." Then, you can use the function std.error()
standard_error_function = std.error(movie_metadata$imdb_score); standard_error_function


